services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: debtmanager-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DebtManager123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - debtmanager-network
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'DebtManager123!' -Q 'SELECT 1' -C || exit 1"
      ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: debtmanager-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DebtManagerDB;User Id=sa;Password=DebtManager123!;TrustServerCertificate=true;
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - debtmanager-network

volumes:
  sqlserver_data:

networks:
  debtmanager-network:
    driver: bridge