// <auto-generated />
using System;
using DebtManager.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DebtManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250703012311_InitialWithTitleNumber")]
    partial class InitialWithTitleNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DebtManager.Core.Domain.Entities.DebtTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRatePerDay")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("OriginalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TitleNumber")
                        .IsUnique();

                    b.ToTable("DebtTitles");
                });

            modelBuilder.Entity("DebtManager.Core.Domain.Entities.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DebtTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DebtTitleId");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("DebtManager.Core.Domain.Entities.DebtTitle", b =>
                {
                    b.OwnsOne("DebtManager.Core.Domain.ValueObjects.Debtor", "Debtor", b1 =>
                        {
                            b1.Property<Guid>("DebtTitleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DebtorName");

                            b1.HasKey("DebtTitleId");

                            b1.ToTable("DebtTitles");

                            b1.WithOwner()
                                .HasForeignKey("DebtTitleId");

                            b1.OwnsOne("DebtManager.Core.Domain.ValueObjects.Document", "Document", b2 =>
                                {
                                    b2.Property<Guid>("DebtorDebtTitleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("DebtorDocumentType");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("DebtorDocument");

                                    b2.HasKey("DebtorDebtTitleId");

                                    b2.ToTable("DebtTitles");

                                    b2.WithOwner()
                                        .HasForeignKey("DebtorDebtTitleId");
                                });

                            b1.Navigation("Document")
                                .IsRequired();
                        });

                    b.Navigation("Debtor")
                        .IsRequired();
                });

            modelBuilder.Entity("DebtManager.Core.Domain.Entities.Installment", b =>
                {
                    b.HasOne("DebtManager.Core.Domain.Entities.DebtTitle", "DebtTitle")
                        .WithMany("Installments")
                        .HasForeignKey("DebtTitleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DebtTitle");
                });

            modelBuilder.Entity("DebtManager.Core.Domain.Entities.DebtTitle", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
